version: '3.9'
services:
  slskd_wanted:
    image: ghcr.io/tommypopescu/slskd_wanted:latest
    container_name: slskd_wanted
    environment:
      - SLSKD_HOST=http://192.168.1.7:5030
      - SLSKD_API_KEY=OXMRJ43VWQU71F9L68TZYHNP
      - SLSKD_CYCLE_PAUSE_MINUTES=30
    volumes:
      - /ssd/appdata/slskd_wanted/wanted.csv:/app/wanted.csv
    ports:
      - "8000:8000"
    restart: always
